### ISSUE TITLE
Why the perfomance of AVS(SAN) model is not good?

### ISSUE THREAD

**Issue by ilovecv** [TheSouthFrog/stylealign#13]
Hi,

Thank you very much for sharing the face landmark model. When I run on my own image, the detection results are not very good. Below is the result of a test image. Did I do something wrong? Thank you very much!

![1](https://user-images.githubusercontent.com/11083384/71771634-39361e00-2ef3-11ea-841b-4b5d2c1c76a6.jpg)

**Comment by TheSouthFrog** [comment]
You need to run a face detector at first to obtain the coordinate of the face bounding box, instead of directly resizing the original image. The reason is that the standard training and testing images are cropped according to their bounding box and fed into the model with a larger size of the face.

**Comment by ilovecv** [comment]
Hi,

Thank you very much for your quick reply. So I tried to preprocess the image you show in crop_pic.py, i.e., pre prop with expand ratio = 0.2, resize image to 256*256. The result is still not very good. Should I expand the face bounding? Here is the result:
![2](https://user-images.githubusercontent.com/11083384/71774588-c6df3100-2f26-11ea-81a9-f4e465503fee.jpg)

**Comment by TheSouthFrog** [comment]
The bounding box you provided is too small. You may expand the ratio then. I guess the result should be improved a lot.

More concretely, you can also refer to this[issue](https://github.com/D-X-Y/landmark-detection/issues/14). The general reason is that you should provide the bounding box with a similar style in your training data, e.g. MTCNN for 300W. Since the model we are using is trained on WFLW. , we are supposed to provide similar box annotations to the Wider Dataset. You can either choose to expand the ratio or use a face detector pre-trained on Wider Face.

**Comment by ilovecv** [comment]
Hi @TheSouthFrog,

As you suggested, I tried another face detector which is trained on Wider face dataset, [https://github.com/TencentYoutuResearch/FaceDetection-DSFD](url)
But still got no luck. 
![2](https://user-images.githubusercontent.com/11083384/71787605-e7fb5c80-2fce-11ea-9c26-ebb8443af46f.jpg)

![1](https://user-images.githubusercontent.com/11083384/71787601-da45d700-2fce-11ea-81b4-b04913f19823.jpg)

Here is the original image:
![2](https://user-images.githubusercontent.com/11083384/71787611-fc3f5980-2fce-11ea-9382-e1a19cfaa660.jpg)

**Comment by TheSouthFrog** [comment]
As I mentioned, the box you provided is too small. have you tried to expand the box ratio? 

Here is an example of cropped out training images which show the proper size of input bounding box.
![WFLW_Train_98pt_7--Cheering_%dir%_7_Cheering_Cheering_7_367 jpg_0000006556](https://user-images.githubusercontent.com/15979295/71790133-c1d6ca80-3069-11ea-9bee-f17b386dbd07.jpg)

**Comment by ilovecv** [comment]
Hi @TheSouthFrog,

I tried to expand the box ratio, it did improve the result. However, for faces with large poses, like the image below, what should I do?
![1](https://user-images.githubusercontent.com/11083384/71794313-ce214000-2ff5-11ea-82be-fb238d2a32a1.jpg)

**Comment by ilovecv** [comment]
Hi @TheSouthFrog,

Now I get good results on landmark detection. And I had trained the variational u-net for the style transfer. However, there is a problem with the result, please see the below image. It looks like the landmarks positions are not correct:
![train_06095](https://user-images.githubusercontent.com/11083384/71797058-6a9d0f80-3001-11ea-9b41-aa347a3cfd18.jpg)
![transfer_0050100](https://user-images.githubusercontent.com/11083384/71797060-6ec92d00-3001-11ea-8cf0-0135ab85cf9d.png)

**Comment by TheSouthFrog** [comment]
Hi, that's actually a very interesting problem in facial landmark detection. One general approach for mitigating large poses is to pre-use a 5-point landmark detector to obtain the basic angles and coordinates, and then align&crop from the original image according to the initial points and then run more fine-grained detector, e.g. 98 points in our case.

**Comment by TheSouthFrog** [comment]
The reason of your second question is that you didn't align the input images first.

If you want to train the generator on your own images, you have to make sure that the landmarks are aligned and centered as well as cropping the corresponding regions of input images. You can refer to the training set I provided which we have pre-processed and cropeed the input raw data.

**Comment by ilovecv** [comment]
Hi @TheSouthFrog,

Thank you very much for your quick response. I learned a lot from it. I am wondering if you can provide the pre-processing script, so I can test on my own images?

**Comment by TheSouthFrog** [comment]
I am sorry that I can't provide my pre-processing script to you since we have shipped the detection, align and crop pipeline into SDK for convenience that might not be able to release.  

However, I would recommend you to re-train the model on your own dataset. Note that in this work we are trying to augment the styles on the originally-available landmarks, thus we didn't emphasize too much on the generalization of unseen images. If the testing image is significantly different from the training ones. The result could be not that great. So I recommend you to first pre-process your data by align&cropping your own training set using some open-sourced script(there are quite a few). And then train a model using the given hyper-parameters. I suppose that way you can see some okay results.

**Comment by ilovecv** [comment]
Hi @TheSouthFrog,

Thank you very much for your suggestions. I am wondering if it is possible for you to point me to some open-sourced scripts for the preprocessing? Thank you very much!

**Comment by TheSouthFrog** [comment]
Sorry for the late response since I missed the notification these days and forget to respond.

I believe the simplest tool you can use is dlib or a similar widely-used package.
